version: "3.9"

services:
  postgresdb:
    container_name: postgresdb
    image: postgres:16.3-alpine3.18
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: futurodev
      POSTGRES_PASSWORD: futurodev123
      POSTGRES_DB: gestordb
    volumes:
      - /Users/joaojoseoliveiraleal/Documents/Database/postgres-futurodev:/var/lib/postgresql/data

  gestorservice:
    container_name: gestorservice
    image: jjleal/gestorservice:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      spring.datasource.url: jdbc:postgresql://postgresdb:5432/gestordb
      spring.datasource.username: futurodev
      spring.datasource.password: futurodev123
    depends_on:
      - postgresdb
